version: "3"

services:
  caddy:
    image: ghcr.io/orangeunilabs/caddy:latest
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    networks:
      - proxynet
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config

    env_file:
      - .env

networks:
  proxynet:
    name: proxynet
    attachable: true
    driver: bridge
