version: "3"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      - proxynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.net.orangeunilabs.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=dashboard@internal"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

    env_file:
      - .env

networks:
  proxynet:
    name: proxynet
    attachable: true
    driver: bridge
