providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    filename: /config.yml

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: acme@orangeunilabs.com
      storage: /certs/cloudflare-acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory

      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "8.8.8.8:53"

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG
  format: json
