certificatesResolvers:
  cloudflare:
    acme:
      email: acme@orangeunilabs.com
      storage: /certs/cloudflare-acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "8.8.8.8:53"
          # - "1.1.1.1:53"
